
version: '3'
services:
  wanglab-jupyter-cmmc-gnps:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wanglab-jupyter-cmmc-gnps
    volumes:
      - .:/home/jovyan/work:rw
    ports:
    - "9303:9000"
    restart: unless-stopped
    command: jupyter lab --ip='*' --port=9000 --no-browser --NotebookApp.token='${LOGINPASSWORD:-PASSWORD}' --allow-root
    networks:
    - default
    - nginx-net
    deploy:
     resources:
       limits:
         memory: 16000M
    environment:
      VIRTUAL_HOST: jupytertemplate.wanglab.science
      VIRTUAL_PORT: 9000
      LETSENCRYPT_HOST: jupytertemplate.wanglab.science
      LETSENCRYPT_EMAIL: mwang87@gmail.com

networks:
  nginx-net:
    external:
      name: nginx-net